version: '3'

services:
  mongo:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      -./data:/data/db

  app:
    build:
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/
    ports:
      - "5000:5000"
    depends_on:
      - mongo